# inventory for this playbook is state db - with a limit of san switches

- name: Configures service accounts on the NetApp systems
  hosts: all
  connection: local
  gather_facts: no
  #vars_files:
   # - "vars/datacenters-{{ lookup('env', 'ANS_REGIONALMODE') }}.yml"
    #- vars/datacenter-networks.yml
  # vars:
  #   ansible_python_interpreter: /var/lib/awx/venv/python3-ansible2.9/bin/python
  roles:
  - role: storageConfigNetAppServiceAccounts
