#Creating a PVC (Physical Volume Claim)
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-disk-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: k3disk #<-- Stoage Class Name you created
  resources:
    requests:
      storage: 1Gi