version: "3"
volumes:
  nextcloud-data:
  nextcloud-db:

networks:
  frontend:
    # add this if the network is already existing!
    external: true
  backend:
    external: true

services:
  nextcloud-app:
    image: nextcloud
    restart: always
	init: true
	container_name: nextcloud-app
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      - MYSQL_PASSWORD="BxFJhQEl96u$R@4HKxxSCn8s2gbY*l"
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
    networks:
      - frontend
      - backend

  nextcloud-db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD="uaL%lEcKsnu7PZCRcYa7&4JPjoivA"
      - MYSQL_PASSWORD="BxFJhQEl96u$R@4HKxxSCn8s2gbY*l"
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend
