---
- hosts: localhost
  gather_facts: false
  name: Connectivity Test & Display ONTAP Info
  tasks:
    - name: "Collect ONTAP info"
      netapp.ontap.na_ontap_rest_info:
        hostname: cluster1.demo.netapp.com
        username: admin
        password: Netapp1!
        https: true
        validate_certs: false
        gather_subset: "svm/svms"
        owning_resource:
          svm_name: "*"
      register: info

    - name: List mapped LUNs using rest-cli modules
      netapp.ontap.na_ontap_rest_info:
        hostname: cluster1.demo.netapp.com
        username: admin
        password: Netapp1!
        gather_subset:
          - protocols/san/lun-maps
        https: true
        validate_certs: false
      register: output

    - name: GET LUN SERIALS
      netapp.ontap.na_ontap_rest_info:
        hostname: cluster1.demo.netapp.com
        username: admin
        password: Netapp1!
        gather_subset:
          - storage/storage_luns_info
        https: true
        validate_certs: false
      register: outlun_info

    - name: Print ONTAP Response
      debug:
        msg: "{{ outlun_info }}"

    - name: Print ONTAP Response
      debug:
        msg: "{{ info }}"

    - name: Print LUN Mappings Response
      debug:
        msg: "{{ output }}"

    - name: Filter LUNs for specified igroup
      set_fact:
        filtered_luns: "{{ output.ontap_info['protocols/san/lun-maps'].records | selectattr('igroup.name', 'equalto', 'ig_' + server | replace('-', '_')) | list }}"
    
    - name: Print filtered LUNs
      debug:
        msg: "{{ filtered_luns }}"
    
    - name: Extract LUN and iGroup details
      set_fact:
        lun_detail: "{{ filtered_luns | map(attribute='lun.name') | list }}"
        igroup_detail: "{{ filtered_luns | map(attribute='igroup.name') | list }}"
        svm_detail: "{{ filtered_luns | map(attribute='svm.name') | list }}"

    - name: Check if LUNs are mapped
      debug:
        msg: "No LUNs mapped to the specified igroup."
      when: lun_detail | length == 0

    - name: Print details of LUNs to be unmapped
      debug:
        msg:
          - "lun name: {{ lun_detail }}"
          - "igroup name: {{ igroup_detail }}"
          - "svm name: {{ svm_detail }}"
      when: lun_detail | length > 0

    - name: Unmap all LUNs
      netapp.ontap.na_ontap_lun_map:
        state: absent
        initiator_group_name: "{{ igroup_name }}"
        path: "{{ lun_name }}"
        vserver: "{{ svm_name }}"
        hostname: "cluster1.demo.netapp.com"
        username: admin
        password: Netapp1!
        https: yes
        validate_certs: no
      loop: "{{ range(0, lun_detail | length) | list }}"
      loop_control:
        label: "{{ lun_detail[item] }}"
      vars:
        lun_name: "{{ lun_detail[item] }}"
        igroup_name: "{{ igroup_detail[item] }}"
        svm_name: "{{ svm_detail[item] }}"
  
