# netapp login settings


# TLS Settings
supported_ciphers:  'ALL:!LOW:!aNULL:!EXP:!eNULL:!3DES:!RC4:!SHA1'
supported_protocols: ['TLSv1.2']

# certification creation defaults
common_name: cluster1.demo.netapp.com
dns_san: "cluster1.demo.netapp.com,cluster1,localhost"
ip_san: "192.168.0.101"
cluster_svm_name: "cluster1"
#ca_project: "{{ lookup('env', 'COMP_PARAMS_PRIVATECAPROJECT') }}"
#ca_issuer_location: "{{ lookup('env', 'COMP_PARAMS_PRIVATECALOCATION') }}"
#ca_issuer_pool: "{{ lookup('env', 'COMP_PARAMS_PRIVATECAPOOL') }}"  

apply_strong_crypto: True
fips_enabled: False